trigger: none

pool:
    vmImage: 'ubuntu-latest'

stages:
    - stage: CI_Build
      jobs:
      - job: CI
        steps:
          - task: CopyFiles@2
            inputs:
              SourceFolder: '$(Build.SourcesDirectory)'
              Contents: |
                **/linkedService/template-json/*.json
                **/dataset/template-json/*.json
                **/pipeline/template-json/*.json
                **/trigger/template-json/*.json
              TargetFolder: '$(Build.ArtifactStagingDirectory)'
              CleanTargetFolder: true
              OverWrite: true
