parameters:
- name: ServiceConnectionName
  type: string
  default: ''
- name: ResourceGroupName
  type: string
  default: ''
- name: DataFactoryName
  type: string
  default: ''
- name: SelfHostedIntegrationRuntimeName
  type: string
  default: ''
- name: IntegrationRuntimeMsiLink
  type: string
  default: 'https://download.microsoft.com/download/E/4/7/E4771905-1079-445B-8BF9-8A1A075D8A10/IntegrationRuntime_5.6.7795.1.msi'

steps:
- powershell: |
   # Downloads Integration Runtime onto the VM
   [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
   New-Item -Path "C:\" -Name "Download" -ItemType "Directory" -Force | Out-Null
   $uri = "${{ parameters.IntegrationRuntimeMsiLink }}"
   Invoke-WebRequest -Uri $uri -OutFile "C:\Download\IntegrationRuntime.msi"  
  displayName: 'Download MSI'
  
- powershell: |
   # Install the Integration Runtime
   msiexec.exe /i "C:\Download\IntegrationRuntime.msi" INSTALLTYPE=AzureTemplate /quiet /norestart
  displayName: 'Install MSI'

- powershell: |
   # Install the AZ Module on the VM
   [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
   Install-PackageProvider nuget -Force -Confirm:$false
   Install-Module -Name Az -AllowClobber -Force -Confirm:$false
  displayName: 'Download and Install AZ Module'

- task: AzurePowerShell@5
  displayName: 'Get a self-hosted IR authentication key'
  inputs:
    azureSubscription: ${{ parameters.ServiceConnectionName }}
    ScriptType: InlineScript
    Inline: |
     # Retrieves Key to register SHIR
     $environmentKeys = Get-AzDataFactoryV2IntegrationRuntimeKey -ResourceGroupName ${{ parameters.ResourceGroupName }} -DataFactoryName ${{ parameters.DataFactoryName }} -Name ${{ parameters.SelfHostedIntegrationRuntimeName }} 
     $environmentKey = $environmentKeys.AuthKey1
     Write-Output ("##vso[task.setvariable variable=SelfHostedIntegrationRuntimeKey]$environmentKey")
    azurePowerShellVersion: LatestVersion

- powershell: |
   # Registers SHIR
   $keyReg = Get-Item "hklm:\Software\Microsoft\DataTransfer\DataManagementGateway\ConfigurationManager"
   $filePath = $keyReg.GetValue("DiacmdPath")
   
   Start-Process -FilePath $filePath -ArgumentList "-Stop" -Wait -Passthru -NoNewWindow
   Start-Process -FilePath $filePath -ArgumentList "-Start" -Wait -Passthru -NoNewWindow
   Start-Process -FilePath $filePath -ArgumentList "-EnableRemoteAccess 8060" -Wait -Passthru -NoNewWindow
   Start-Process -FilePath $filePath -ArgumentList "-RegisterNewNode $(SelfHostedIntegrationRuntimeKey)" -Wait -Passthru -NoNewWindow
   Start-Process -FilePath $filePath -ArgumentList "-Key $(SelfHostedIntegrationRuntimeKey)" -Wait -Passthru -NoNewWindow 
  displayName: 'Register SHIR'
 
- task: PowerShell@2
  displayName: 'Enable only TLS 1.2 on SHIR'
  inputs:
    targetType: filePath
    filePath: './scripts/EnableTLS.ps1'
